import { Appliance } from '../types';

export const DEFAULT_APPLIANCES: Appliance[] = [
  {
    id: 'hvac',
    name: 'HVAC / Air Conditioning',
    icon: 'thermometer',
    wattage: 3500,
    hoursPerDay: 6,
    quantity: 1,
  },
  {
    id: 'water-heater',
    name: 'Water Heater',
    icon: 'water',
    wattage: 4000,
    hoursPerDay: 2,
    quantity: 1,
  },
  {
    id: 'refrigerator',
    name: 'Refrigerator',
    icon: 'restaurant',
    wattage: 150,
    hoursPerDay: 24,
    quantity: 1,
  },
  {
    id: 'washer-dryer',
    name: 'Washer & Dryer',
    icon: 'shirt',
    wattage: 3000,
    hoursPerDay: 1.5,
    quantity: 1,
  },
  {
    id: 'dishwasher',
    name: 'Dishwasher',
    icon: 'water-outline',
    wattage: 1800,
    hoursPerDay: 1,
    quantity: 1,
  },
  {
    id: 'lighting',
    name: 'LED Lighting',
    icon: 'bulb',
    wattage: 200,
    hoursPerDay: 6,
    quantity: 1,
  },
  {
    id: 'ev-charger',
    name: 'EV Charger (Level 2)',
    icon: 'car',
    wattage: 7200,
    hoursPerDay: 2,
    quantity: 0,
  },
  {
    id: 'pool-pump',
    name: 'Pool Pump',
    icon: 'water',
    wattage: 1500,
    hoursPerDay: 6,
    quantity: 0,
  },
  {
    id: 'tv',
    name: 'Television & Entertainment',
    icon: 'tv',
    wattage: 150,
    hoursPerDay: 5,
    quantity: 1,
  },
  {
    id: 'desktop',
    name: 'Computers & Devices',
    icon: 'desktop',
    wattage: 200,
    hoursPerDay: 8,
    quantity: 1,
  },
  {
    id: 'oven',
    name: 'Electric Oven / Range',
    icon: 'flame',
    wattage: 2400,
    hoursPerDay: 1,
    quantity: 1,
  },
  {
    id: 'hot-tub',
    name: 'Hot Tub / Spa',
    icon: 'water',
    wattage: 5500,
    hoursPerDay: 1.5,
    quantity: 0,
  },
];
