import { RegionData } from '../types';

export const REGIONS: RegionData[] = [
  {
    city: 'Phoenix',
    state: 'AZ',
    country: 'USA',
    peakSunHoursPerDay: 6.5,
    averageElectricityRate: 0.125,
    stateIncentivePercent: 0,
    incentiveNotes: 'AZ offers a personal tax credit of 25% (up to $1,000).',
    timezone: 'America/Phoenix',
    lat: 33.4484,
    lng: -112.074,
  },
  {
    city: 'Los Angeles',
    state: 'CA',
    country: 'USA',
    peakSunHoursPerDay: 5.62,
    averageElectricityRate: 0.27,
    stateIncentivePercent: 0,
    incentiveNotes: 'CA Self-Generation Incentive Program (SGIP) available.',
    timezone: 'America/Los_Angeles',
    lat: 34.0522,
    lng: -118.2437,
  },
  {
    city: 'San Francisco',
    state: 'CA',
    country: 'USA',
    peakSunHoursPerDay: 5.32,
    averageElectricityRate: 0.32,
    stateIncentivePercent: 0,
    incentiveNotes: 'CA SGIP; SF offers additional rebates through CleanPowerSF.',
    timezone: 'America/Los_Angeles',
    lat: 37.7749,
    lng: -122.4194,
  },
  {
    city: 'Las Vegas',
    state: 'NV',
    country: 'USA',
    peakSunHoursPerDay: 6.41,
    averageElectricityRate: 0.12,
    stateIncentivePercent: 0,
    incentiveNotes: 'NV Energy net metering available.',
    timezone: 'America/Los_Angeles',
    lat: 36.1699,
    lng: -115.1398,
  },
  {
    city: 'Miami',
    state: 'FL',
    country: 'USA',
    peakSunHoursPerDay: 5.26,
    averageElectricityRate: 0.135,
    stateIncentivePercent: 0,
    incentiveNotes: 'FL offers property tax exemption for solar installations.',
    timezone: 'America/New_York',
    lat: 25.7617,
    lng: -80.1918,
  },
  {
    city: 'Houston',
    state: 'TX',
    country: 'USA',
    peakSunHoursPerDay: 5.27,
    averageElectricityRate: 0.118,
    stateIncentivePercent: 0,
    incentiveNotes: 'TX property tax exemption (100%) for added home value from solar.',
    timezone: 'America/Chicago',
    lat: 29.7604,
    lng: -95.3698,
  },
  {
    city: 'New York City',
    state: 'NY',
    country: 'USA',
    peakSunHoursPerDay: 4.79,
    averageElectricityRate: 0.23,
    stateIncentivePercent: 25,
    incentiveNotes: 'NY state tax credit up to $5,000 (25%); NYC SolarMap incentives.',
    timezone: 'America/New_York',
    lat: 40.7128,
    lng: -74.006,
  },
  {
    city: 'Chicago',
    state: 'IL',
    country: 'USA',
    peakSunHoursPerDay: 4.08,
    averageElectricityRate: 0.135,
    stateIncentivePercent: 0,
    incentiveNotes: 'IL Adjustable Block (AB) solar incentive program available.',
    timezone: 'America/Chicago',
    lat: 41.8781,
    lng: -87.6298,
  },
  {
    city: 'Seattle',
    state: 'WA',
    country: 'USA',
    peakSunHoursPerDay: 3.57,
    averageElectricityRate: 0.105,
    stateIncentivePercent: 0,
    incentiveNotes: 'WA sales tax exemption for solar equipment purchases.',
    timezone: 'America/Los_Angeles',
    lat: 47.6062,
    lng: -122.3321,
  },
  {
    city: 'Denver',
    state: 'CO',
    country: 'USA',
    peakSunHoursPerDay: 5.46,
    averageElectricityRate: 0.135,
    stateIncentivePercent: 0,
    incentiveNotes: 'CO sales tax exemption; Xcel Energy rebates available.',
    timezone: 'America/Denver',
    lat: 39.7392,
    lng: -104.9903,
  },
  {
    city: 'Boston',
    state: 'MA',
    country: 'USA',
    peakSunHoursPerDay: 4.53,
    averageElectricityRate: 0.245,
    stateIncentivePercent: 15,
    incentiveNotes: 'MA SMART program pays per kWh produced; 15% state tax credit.',
    timezone: 'America/New_York',
    lat: 42.3601,
    lng: -71.0589,
  },
  {
    city: 'Atlanta',
    state: 'GA',
    country: 'USA',
    peakSunHoursPerDay: 5.16,
    averageElectricityRate: 0.12,
    stateIncentivePercent: 0,
    incentiveNotes: 'GA Clean Energy Property Tax Credit available.',
    timezone: 'America/New_York',
    lat: 33.749,
    lng: -84.388,
  },
  {
    city: 'Austin',
    state: 'TX',
    country: 'USA',
    peakSunHoursPerDay: 5.44,
    averageElectricityRate: 0.115,
    stateIncentivePercent: 0,
    incentiveNotes: 'Austin Energy offers rebates up to $2,500 for residential solar.',
    timezone: 'America/Chicago',
    lat: 30.2672,
    lng: -97.7431,
  },
  {
    city: 'San Diego',
    state: 'CA',
    country: 'USA',
    peakSunHoursPerDay: 5.98,
    averageElectricityRate: 0.295,
    stateIncentivePercent: 0,
    incentiveNotes: 'SDG&E net metering NEM 3.0 in effect; CA SGIP applicable.',
    timezone: 'America/Los_Angeles',
    lat: 32.7157,
    lng: -117.1611,
  },
  {
    city: 'Other',
    state: 'N/A',
    country: 'USA',
    peakSunHoursPerDay: 4.8,
    averageElectricityRate: 0.16,
    stateIncentivePercent: 0,
    incentiveNotes: 'Check your state and utility for available incentives.',
    timezone: 'America/New_York',
    lat: 39.5,
    lng: -98.35,
  },
];

export const getRegionByCity = (city: string): RegionData => {
  return (
    REGIONS.find((r) => r.city.toLowerCase() === city.toLowerCase()) ||
    REGIONS[REGIONS.length - 1]
  );
};
