import { SolarPanel } from '../types';

export const SOLAR_PANELS: SolarPanel[] = [
  // ── Premium Tier ──────────────────────────────────────────────────────────
  {
    id: 'sunpower-maxeon-6',
    brand: 'SunPower',
    model: 'Maxeon 6',
    wattage: 440,
    efficiency: 22.8,
    dimensions: { lengthInches: 72.8, widthInches: 40.9 },
    areaSquareFeet: 20.7,
    pricePerPanel: 420,
    warranty: 40,
    degradationRate: 0.25,
    type: 'monocrystalline',
    tier: 'premium',
  },
  {
    id: 'rec-alpha-pure-r',
    brand: 'REC',
    model: 'Alpha Pure-R 430',
    wattage: 430,
    efficiency: 22.3,
    dimensions: { lengthInches: 70.4, widthInches: 41.8 },
    areaSquareFeet: 20.4,
    pricePerPanel: 380,
    warranty: 25,
    degradationRate: 0.25,
    type: 'monocrystalline',
    tier: 'premium',
  },
  {
    id: 'lg-neon-r',
    brand: 'LG',
    model: 'NeON R 405',
    wattage: 405,
    efficiency: 22.1,
    dimensions: { lengthInches: 66.9, widthInches: 40.0 },
    areaSquareFeet: 18.6,
    pricePerPanel: 370,
    warranty: 25,
    degradationRate: 0.3,
    type: 'monocrystalline',
    tier: 'premium',
  },

  // ── Standard Tier ────────────────────────────────────────────────────────
  {
    id: 'qcells-q-peak-duo',
    brand: 'Q CELLS',
    model: 'Q.PEAK DUO BLK ML-G10+ 395',
    wattage: 395,
    efficiency: 20.6,
    dimensions: { lengthInches: 70.9, widthInches: 40.9 },
    areaSquareFeet: 20.1,
    pricePerPanel: 290,
    warranty: 25,
    degradationRate: 0.5,
    type: 'monocrystalline',
    tier: 'standard',
  },
  {
    id: 'canadian-solar-hiku6',
    brand: 'Canadian Solar',
    model: 'HiKu6 Mono PERC CS6R-385',
    wattage: 385,
    efficiency: 20.3,
    dimensions: { lengthInches: 70.2, widthInches: 40.9 },
    areaSquareFeet: 19.9,
    pricePerPanel: 265,
    warranty: 25,
    degradationRate: 0.55,
    type: 'monocrystalline',
    tier: 'standard',
  },
  {
    id: 'jinko-tiger-neo',
    brand: 'Jinko Solar',
    model: 'Tiger Neo N-type 72HL4-V 580',
    wattage: 580,
    efficiency: 22.02,
    dimensions: { lengthInches: 87.6, widthInches: 44.3 },
    areaSquareFeet: 27.0,
    pricePerPanel: 340,
    warranty: 25,
    degradationRate: 0.4,
    type: 'monocrystalline',
    tier: 'standard',
  },
  {
    id: 'longi-hi-mo-6',
    brand: 'LONGi',
    model: 'Hi-MO 6 Scientist LR5-54HTH 415M',
    wattage: 415,
    efficiency: 21.3,
    dimensions: { lengthInches: 70.5, widthInches: 40.9 },
    areaSquareFeet: 20.0,
    pricePerPanel: 280,
    warranty: 25,
    degradationRate: 0.45,
    type: 'monocrystalline',
    tier: 'standard',
  },

  // ── Budget Tier ───────────────────────────────────────────────────────────
  {
    id: 'trina-vertex-s',
    brand: 'Trina Solar',
    model: 'Vertex S+ NEG9R.28 425',
    wattage: 425,
    efficiency: 21.8,
    dimensions: { lengthInches: 71.6, widthInches: 40.9 },
    areaSquareFeet: 20.4,
    pricePerPanel: 240,
    warranty: 25,
    degradationRate: 0.5,
    type: 'monocrystalline',
    tier: 'budget',
  },
  {
    id: 'risen-titan-s',
    brand: 'Risen Energy',
    model: 'Titan S RSM40-8-400M',
    wattage: 400,
    efficiency: 20.9,
    dimensions: { lengthInches: 70.1, widthInches: 40.9 },
    areaSquareFeet: 19.9,
    pricePerPanel: 210,
    warranty: 20,
    degradationRate: 0.6,
    type: 'monocrystalline',
    tier: 'budget',
  },
  {
    id: 'boviet-bvm6612m',
    brand: 'Boviet Solar',
    model: 'BVM6612M-375',
    wattage: 375,
    efficiency: 19.4,
    dimensions: { lengthInches: 70.5, widthInches: 40.2 },
    areaSquareFeet: 19.7,
    pricePerPanel: 185,
    warranty: 20,
    degradationRate: 0.65,
    type: 'polycrystalline',
    tier: 'budget',
  },
];

export const INVERTER_COST_PER_KW = 250; // USD per kW (string inverter)
export const MICROINVERTER_COST_PER_PANEL = 180; // USD per panel
export const INSTALLATION_COST_PER_KW = 700; // USD per kW
export const PERMIT_COST = 500; // USD flat
export const FEDERAL_TAX_CREDIT = 0.30; // 30% ITC
export const SYSTEM_DEGRADATION_RATE = 0.005; // 0.5% per year (blended)
export const ELECTRICITY_ESCALATION_RATE = 0.025; // 2.5% per year
export const PANEL_AREA_BUFFER = 0.85; // only 85% of calculated panels fit neatly
